### ISSUE TITLE
Canvas is not showing(with solution)

### ISSUE THREAD

**Issue by RupenderT** [selemxmn/ngx-print#105]
**Is your feature request related to a problem? Please describe.**
Hello  there, currenlty this ngx-print is not printing any canvas so I would  suggest you to upgrade getHtmlContent 
like this

private getHtmlContents() {
        let printContents = document.getElementById(this.printSectionId);
        let innards = printContents.getElementsByTagName('input');
        for (var i = 0; i < innards.length; i++) {
            innards[i].defaultValue = innards[i].value;
        }
        let canvas = printContents.getElementsByTagName('canvas');
        for (let i = 0; i < canvas.length; i++) {
            const e = canvas[i];
            var img = document.createElement('img');
            img.className = e.className;
            img.style.cssText = e.getAttribute('style');
            img.src=e.toDataURL();
            e.parentElement.replaceChild(img, e);
        }
        return printContents.innerHTML;
    }

**Comment by diogoduailibe** [comment]
@RupenderT Thank's for sharing this solution! This really solves the issue, but it has a side effect if you use `ng2-charts` for example. 

With the use of `e.parentElement.replaceChild`, it removes `<canvas>` from the original html, replacing by `<img>` element. And because of that, some interactions from charts cease to exist.

In this case, the suggestion would be creating a `print-section` div **clone** so that the changes doesn't affect the original div. And the return of `getHtmlContents` would be `innerHTML` from cloned div instead.

Besides that, in tests that I executed locally, I realized that the cloned div doesn't bring `<canvas>` correctly on `<img>` element generation. So the `<img>` element should be created based on original `print-section` div, but replaced on cloned div.

Here is the code:

```javascript
getHtmlContents() {        
    let printContents = document.createElement('div');
    printContents.innerHTML = document.getElementById(this.printSectionId).innerHTML;
      
    let innards = printContents.getElementsByTagName('input');
    for (var i = 0; i < innards.length; i++) {
        innards[i].defaultValue = innards[i].value;
    }

    const canvas = Array.from(document.getElementsByTagName('canvas'));
    const canvasClone = Array.from(printContents.getElementsByTagName('canvas'))

    for (var i = 0; i < canvas.length; i++) {
      const e = canvas[i];
      const eClone = canvasClone[i];
      const img = document.createElement('img');
      img.className = e.className;
      img.style.cssText = e.getAttribute('style');
      img.src = e.toDataURL();
      eClone.parentNode.replaceChild(img, eClone);
    };

    return printContents.innerHTML;
}
```

Hope it helps!

**Comment by tripathiarpit** [comment]
@diogoduailibe I still see the issue while printing a component that has canvas, it is actually not printing the whole image, but 1/4 of it.
