### ISSUE TITLE
Ngx-Print, Print dialog box is very small in Microsoft Edge.

### ISSUE THREAD

**Issue by SandeepAbbaiah** [selemxmn/ngx-print#195]
**Describe the bug**
Print Dialog box is very small in Microsoft Edge but it displays correct size in Chrome

**To Reproduce**
Steps to reproduce the behavior.
Try Print in Microsoft edge

**Expected behavior**
Print dialog box should be bigger in size

**Screenshots**
**Microsoft Edge :**
![image](https://github.com/user-attachments/assets/515bbf9f-5f6e-4e8a-add1-6dc559f155e3)

Chrome : 
![image](https://github.com/user-attachments/assets/2c26ebc4-ec07-487d-95c2-2d59de41a3d0)

**Ngx-Print Version**
Include the current affected version.
v1.5.1

**Desktop (please complete the following information):**
 - Browser [chrome, safari]

**Additional context**

**Comment by SandeepAbbaiah** [comment]
@Core121 @selemxmn - Please help in this

**Comment by Core121** [comment]
Looks like your layout in edge is likely in landscape mode while your chrome layout is portrait. The layout on edge is cutoff so I'm only speculating.

**Comment by SandeepAbbaiah** [comment]
It's Portrait mode in Edge.
![image](https://github.com/user-attachments/assets/203876d7-5bd7-439f-818b-0245996139f8)

**Comment by SandeepAbbaiah** [comment]
Default Print(Ctrl + P) has correct size and the preview page looks good and readable. But with ngx-print it looks very small and not clear.

Print dialog box with ctrl + p :
![image](https://github.com/user-attachments/assets/178c2a94-7801-4a96-97e5-5336f476df1b)

**Comment by Core121** [comment]
It seems the layout was previously in landscape mode, but the view has now changed. Please note that screen orientation is determined by your browser settings and falls outside the scope of what ngx-print can control.

When using Ctrl + P, you're printing the entire page, including elements like the StackBlitz interface. ngx-print, however, is designed to print only the content rendered by Angular. You will need to edit your css to make the table larger when printing since the view is likely resizing in stackblitz due to limited space in the rendered window.

**Comment by Sandeep-Abbaiah** [comment]
@Core121 - Yes agree. I just gave you an example on how it works.
So, the problem with ngx-print is still unresolved.
The orientation is still Portrait. I haven't changed it.
You can try replicating same issue in Microsoft Edge. You should get it.
