### ISSUE TITLE
styles are not being set appropriately

### ISSUE THREAD

**Issue by davideng14** [selemxmn/ngx-print#25]
I am trying to set styles to component as is described in the documentation but these are not taken by the plugin. It seems like only take the first style of each element or styles with only one property (i.e `h1{font-weight: bold }`).

**To Reproduce**
1. Create a new angular 7 application.
2. ng new library print-lib
3. set styles with several rules on them.
`<button type="button" class="btn btn-primary"
  [printStyle]="{ div: {'width': '2.025in', 'height': '.875in', 'padding':'.125in .3in 0', 'margin-right':'.125in', 'display':'inline-block'}, label: {'display':'block', 'white-space': 'nowrap', 'overflow':'hidden', 'font-size':'5px'}, img: {'max-width':'40%'}}"
          printSectionId="print-section" ngxPrint>show modal</button>`

**Expected behavior**
Take and apply all the styles appropriately.

 - Mac OS High Sierra
 - Chrome
 - Version: 1.1.4

**Comment by silenceway** [comment]
This is happening because the browser's javascript only changes the first comma in string replace and this line is returning a malformed string:
`return this._printStyle.join(' ').replace(',', ';');`
It's better to use regexp in replace in this case:
`return this._printStyle.join(' ').replace(/,/g, ';');`
This behavior can be tested here: https://jsfiddle.net/a3wgL9yh/
When you click button, it only changes first comma.
Thanks.

**Comment by selemxmn** [comment]
@davideng14 Thank you for using `ngx-print`, that was indeed a bug and @silenceway thanks , it was indeed the problem there. Will be fixed soon , stay tuned :)

**Comment by s91firm** [comment]
I was facing the styles issue as well - some were being applied while others were being omitted. Thankfully placing inline styles works just fine (hopefully a temporary workaround only!)

**Comment by selemxmn** [comment]
@s91firm , actaully that was already fixed an committed in a specific branch, i.e : not released yet.
 Very soon you'll get it in `ngx-print@1.2.0`. Stay tuned.
