### ISSUE TITLE
Font Awesome icon not getting printed with ngx-print

### ISSUE THREAD

**Issue by agamgupta6** [selemxmn/ngx-print#47]
Font awesome icon is not reflecting in the print preview with ngx-print. When doing Ctrl+P, it is getting reflected properly in the Print preview section. 

**Original Screen**

![Original page](https://user-images.githubusercontent.com/11807952/63105367-4b182400-bf46-11e9-9d1a-210f358da5ae.png)

**Print with Ctrl+P**

![Print manually](https://user-images.githubusercontent.com/11807952/63105403-566b4f80-bf46-11e9-9999-a90ded68e434.png)

**Print with ngx-print**

![print with ngx print](https://user-images.githubusercontent.com/11807952/63105445-67b45c00-bf46-11e9-8145-9c1762d721b5.png)

**Comment by manoj150283** [comment]
Any workaround solution for this ?

**Comment by davemecha** [comment]
I have a similar problem. I want to use a special font in my custom css, that is provided via `styleSheetFile`.

```
@font-face {
  src: url("/assets/vendor/umba-sans-bold-font/font.ttf");
  font-family: UmbaSansBold;
}
```

The text just don't get rendered, when I do something like this:

```
.heading {
  font-family: UmbaSansBold;
}
```

This is because the font is not loaded in the popup when the print command is called.

I checked the code and found out, that there is this `onload` event triggered on popup load.

```
onload="window.print(); setTimeout(()=>{ window.close(); }, 0)"
```

I just tried out a hot fix and tried to wait half a second before printing:

```
onload="setTimeout(()=>{window.print(); setTimeout(()=>{ window.close(); }, 0);}, 500)"
```

With this the font gets loaded and I get the correct output. I'm not sure if this is a good hack. Maybe there is a better way to check when all resources are loaded.
